### ISSUE TITLE
Structures floating halfway in air

### ISSUE THREAD

**Issue by marcelschoen** [ryandw11/CustomStructures#120]
With larger structures like this house, they often end up halfway floating in the air, despite "air" not being configured in the whitelist of blocks to put the structure on.

![image](https://user-images.githubusercontent.com/1741855/136600060-82a36ab1-d07f-489b-830e-d0b3e0f55c73.png)

This is the location config of this house:

```
StructureLocation:
  Worlds:
    - Hardcore Survival
  SpawnY: top
  SpawnYHeightMap: 'WORLD_SURFACE'
  CalculateSpawnFirst: true
  Biome: 
    - desert
    - desert_hills
  DistanceFromOthers: 100
  # Set a custom spawn distance for the structures.
  spawn_distance:
    x: 10
    z: 10

StructureProperties:
  PlaceAir: true
  randomRotation: true
  ignorePlants: true
  spawnInWater: false
  spawnInLavaLakes: false
  spawnInVoid: false

StructureLimitations:
  whitelistSpawnBlocks:
    - sand
    - sandstone
    - Stone
```

Am I doing something wrong?
