### ISSUE TITLE
Invalid enchantment names / documentation outdated?

### ISSUE THREAD

**Issue by marcelschoen** [ryandw11/CustomStructures#121]
I created loot tables with enchanted gear, for example like this:

```
  helmet_enchanted_1:
    Type: 'IRON_HELMET'
    Amount: 1
    Weight: 4
    Enchantments:
      PROTECTION_ENVIRONMENTAL: 1
```
In the console I then see errors like this one:
```
INFO com.ryandw11.structure.exceptions.LootTableException: Invalid Enchantment: PROTECTION_ENVIRONMENTAL
```
However, the loot table Wiki topic 

* https://github.com/ryandw11/CustomStructures/wiki/Loot-Tables#items

explicitely refers to this URL for documentation of the enchantment names:

* https://hub.spigotmc.org/javadocs/spigot/org/bukkit/enchantments/Enchantment.html

And on that page, "PROTECTION_ENVIRONMENTAL" is one of the constants. So something does not add up for me.

FYI, I am running a Minecraft 1.17.1 Paper server:

```
09.10 15:48:51 [Server] INFO Starting minecraft server version 1.17.1
09.10 15:48:51 [Server] INFO Loading properties
09.10 15:48:51 [Server] INFO This server is running Paper version git-Paper-279 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 6de48db)
```
