### ISSUE TITLE
Allow vertical reposition for sub-schematics

### ISSUE THREAD

**Issue by AllayBreeze** [ryandw11/CustomStructures#164]
**Is your feature request related to a problem? Please describe.**
The current sub-schematic mechanism is very suitable for single structures with multiple parts (such as dungeons and fortresses), but not so suitable for building groups (such as villages and towns), because the heights of sub-schematics are always fixed, which leads to the situation that if use sub-structures to make single buildings in a building group, the buildings in uneven areas often float or be buried underground.

**Describe the solution you'd like**
Add a new option "VerticalRepositions" to sub-schematics, as an example below:

```yml
schem1:
      File: 'schem1.schem'
      PlaceAir: false
      UseRotation: true
      VerticalRepositions:
         Enabled: true
         Range: [-10;20] #The vertical range limit that the reposition can be executed. In this example this sub-schematic can be vertically repositioned down to 10 blocks or up to 20 blocks.
         SpawnY: top #Similar to StructureLocations.
         SpawnYHeightMap: 'WORLD_SURFACE' #Similar to StructureLocations. This and SpawnY can be used to determine which point should the sub-schematic be repositioned to.
         NoPointSolution: UNUSE #Determines if cannot find any suitable points satisfying SpawnY and SpawnYHeightMap, what operation should do next. UNUSE means not to paste the sub-schematic anymore, ORIGIN means paste the sub-schematic at the originally [schem] sign. RANDOM means randomly paste the sub-schematic within the range.
```

With these vertical reposition settings, all buildings in a building groups can correctly be generated on surface even when on peaks or slopes.

**Describe alternatives you've considered**
A new system that is independent to sub-schematic mechanism and more suitable for building groups (same as #76).
