### ISSUE TITLE
Problems with mob spawning

### ISSUE THREAD

**Issue by tr330ne** [ryandw11/CustomStructures#20]
I put a sign, wrote the text, added it to the schematic, reinstalled the world, and no one appeared at the place of the sign and it did not disappear
![2019-07-27_12 36 42](https://user-images.githubusercontent.com/53233736/61992979-02b7c580-b06e-11e9-9a9f-2fa52876a2fe.png)

**Comment by ryandw11** [comment]
Do not include the brackets {}

**Comment by tr330ne** [comment]
And after I create the world, the illusionists will not run away until players find a dungeon?

**Comment by ryandw11** [comment]
The dungeon will not spawn until a player gets close to it.

**Comment by tr330ne** [comment]
And how can I be sure that the dungeon does not recover or retire after the player leaves and another arrives?

**Comment by ryandw11** [comment]
Structures only spawn in new chucks. One a dungeon has been discovered and raided it stays that way.

**Comment by tr330ne** [comment]
But the server on spigot unloads chunks?

**Comment by ryandw11** [comment]
Yes the chunks are unloaded. Spigot keeps tracks of when it generates completely new chucks. The plugin only spawns structures on brand new chunks.

**Comment by tr330ne** [comment]
And if you know, how many need to put a megabyte in xmx and xms in the Start.sh file if the VDS has allocated a maximum of 7168 RAM?  Xmx - the maximum amount of RAM allocated to the server.
 Xms - the minimum amount of RAM allocated to the server.

**Comment by ryandw11** [comment]
It really doesn't matter. I wouldn't go below 1 GB though.

**Comment by tr330ne** [comment]
If I add a new dungeon, it will simply be automatically generated in that world - in which I will choose? And how to add a few dungeons and not one? And how to write new dungeon in the config?

**Comment by ryandw11** [comment]
Sorry for taking so long to reply. To create another dragon just copy and paste your yaml for the dungeon above. Example: 
```yml
configversion: 3
#========================================
#             Custom Structures    
#========================================
#Wiki: https://github.com/ryandw11/CustomStructures/wiki

#Allow Plugins to delete structures at will.
allowDeletion: true

Schematics:
    #Change the name bellow with what you want.
    demo:
        #The schematic file. Make sure to include the .schem
        Schematic: 'demo.schem'
        #What biome this a schematic can spawn in. Change to all for all.
        Biome: 'all'
        #The chance option
        Chance:
            #The number that can be picked out of 1000. So if 1 is picked than it spawns.
            Number: 1
            #The number that the ratio is out off.
            OutOf: 1000
        #If the structure can spawn in all worlds.
        AllWorlds: true
        #If the above is false then the worlds it can spawn in:
        AllowedWorlds:
            - world
        #The y cord the structure will spawn on. Use top if you want it to be on the surface.
        SpawnY: top
        #If you want air to be placed. True is air will be placed. False is air won't be placed.
        PlaceAir: true
        #If you want the structure to spawn in water or lava.
        spawnInLiquid: false
        #If the structure should be randomly rotated.
        randomRotation: false
        #Whitelisted blocks that the structure can spawn on. Remove this list if you do not want a whitelist.
        whitelistSpawnBlocks:
            - Grass_block
            - Dirt
            - Stone
            - air
        #List of lootTables for this Schematic, name and weight
        #Weight determines how often it will be chosen out of all the entries in the list.
        LootTables:
            lootTable: 5

    dungeon2:
        Schematic: 'dungeon2.schem'
        Biome: 'all'
        Chance:
            Number: 1
            OutOf: 1000
        AllWorlds: true
        AllowedWorlds:
            - world
        SpawnY: +[10-20]
        PlaceAir: true
        spawnInLiquid: false
        randomRotation: false
        whitelistSpawnBlocks:
            - Grass_block
            - Dirt
            - Stone
            - air
        LootTables:
            anotherLootable: 5
            lootTable: 3
```
