### ISSUE TITLE
Mobs and LootTabes fail to load.

### ISSUE THREAD

**Issue by lowkeyHero** [ryandw11/CustomStructures#23]
paperSpigot 1.14.4 - plugin version 1.4.2.1

I have a fully configured set of lootTables and they keep erroring when a new structure is generated.  
https://pastebin.com/efEwgP95
https://pastebin.com/7eZafJQZ

Also, vanilla mobs don't spawn at the signs as they are supposed to.  I have not turned on random rotation.  

<img width="1440" alt="Screen Shot 2019-08-13 at 8 22 06 PM" src="https://user-images.githubusercontent.com/34981581/62992540-b5c34580-be08-11e9-87c3-1e157d8e3c79.png">

I have gone through all of the files to be sure enchants and item names are correct. not sure why the error keeps coming back null.

here are the configs:
loottable.yml - https://pastebin.com/QVfkzVb7
loottable2.yml - https://pastebin.com/ciM9uxJE 
loottable3.yml -  https://pastebin.com/k894PMaG 
and config.yml - https://pastebin.com/R7RVHavL

**Comment by ryandw11** [comment]
Are your loot tables lootTable.yml or loottable,yml?

**Comment by lowkeyHero** [comment]
They are loottable.yml , loottable2.yml ....

**Comment by ryandw11** [comment]
Ok found the problem. All of your loot tables have capitalization.
```yaml
LootTables:
            lootTable: 4
            lootTable2: 3
            lootTable3: 5
```
They need to be
```yaml
LootTables:
            loottable: 4
            loottable2: 3
            loottable3: 5
```
