### ISSUE TITLE
The problem with spawn on the surface

### ISSUE THREAD

**Issue by JanekRProrok** [ryandw11/CustomStructures#29]
Hi. I want to use your plugin to differentiate the map on my small server. I mean add ruins, dead trees, abandoned camps, etc.
I created a fallen tree scheme for the test, but I have a problem setting its spawn directly on the surface. As height _y_ I used both settings which I found  `top` and `-1`. Finally, I also removed `dirt` from _whitelistSpawnBlocks_.
Can you help me with this?

Below I put my config and screenshots of sample effects of the plugin.
```
configversion: 3
#========================================
#             Custom Structures    
#========================================
#Wiki: https://github.com/ryandw11/CustomStructures/wiki

#Allow Plugins to delete structures at will.
allowDeletion: true

Schematics:
    #Change the name bellow with what you want.
    UpadleDrzewo:
        #The schematic file. Make sure to include the .schem
        Schematic: 'UpadleDrzewo.schem'
        #What biome this a schematic can spawn in. Change to all for all.
        Biome: 'all'
        #The chance option
        Chance:
            #The number that can be picked out of 1000. So if 1 is picked than it spawns.
            Number: 1
            #The number that the ratio is out off.
            OutOf: 3
        #If the structure can spawn in all worlds.
        AllWorlds: true
        #If the above is false then the worlds it can spawn in:
        AllowedWorlds:
            - world
        #The y cord the structure will spawn on. Use top if you want it to be on the surface.
        SpawnY: -1
        #If you want air to be placed. True is air will be placed. False is air won't be placed.
        PlaceAir: true
        #If you want the structure to spawn in water or lava.
        spawnInLiquid: false
        #If the structure should be randomly rotated.
        randomRotation: true
        #Whitelisted blocks that the structure can spawn on. Remove this list if you do not want a whitelist.
        whitelistSpawnBlocks:
            - Grass_block
            - Stone
            - air
            - sand
```
![2019-11-07_20 18 37](https://user-images.githubusercontent.com/43524378/68420395-908e6b00-019c-11ea-9313-691b311002a8.png)
![2019-11-07_20 18 20](https://user-images.githubusercontent.com/43524378/68420396-91270180-019c-11ea-9522-765fbe677b2a.png)
![2019-11-07_20 07 45](https://user-images.githubusercontent.com/43524378/68420397-91270180-019c-11ea-83db-9efb07c9933e.png)
![2019-11-07_19 54 49](https://user-images.githubusercontent.com/43524378/68420398-91270180-019c-11ea-80d8-30e6a6ff71f9.png)
![2019-11-07_20 19 11](https://user-images.githubusercontent.com/43524378/68420400-91270180-019c-11ea-9286-c3fd4d747295.png)
![2019-11-07_20 19 00](https://user-images.githubusercontent.com/43524378/68420401-91bf9800-019c-11ea-89d3-f83154063792.png)
